---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  environments_path: './test/environments'
  roles_path: './test/roles'

platforms:
  - name: ubuntu-12.04
suites:
  - name: default
    run_list:
      - recipe[aem_disp_config::default]
    attributes:
    provisioner:
        client.rb:
            environment: aem_uat
            role: cruorg_apache_conf
